### ISSUE TITLE
about file download

### ISSUE THREAD

**Issue by ShuaibZyx** [NIRVANALAN/E3DGE#5]
Hello, There is no file download sentence about "pretrained_renderer/ffhq1024x1024_vol_renderer.pt" in file "download_models.py," is this file downlaod from other way or something I deal with is wrong? Thanks your answer
![{9EABBF94-9F95-4ee0-962C-409240101B70}](https://github.com/NIRVANALAN/CVPR23-E3DGE/assets/106308226/0dc814b5-3910-46fb-ab95-5b1028517edb)
.

**Comment by NIRVANALAN** [comment]
Hi, I guess it should be downloaded here? https://github.com/NIRVANALAN/CVPR23-E3DGE/blob/7666d5bb05ed9a6ff43000c43ffb5dca8305871d/download_models.py#L47
