### ISSUE TITLE
An issue about `--not_apply_que_weight` in `demo_editing.sh`

### ISSUE THREAD

**Issue by Twizwei** [NIRVANALAN/E3DGE#7]
Thanks for sharing the code!  Not sure if this has been raised before, but there was an issue I found when I ran `bash scripts/test/demo_editing.sh`. It is about the argument `--not_apply_que_weight`. I ended up with commenting it out and the script worked.

**Comment by NIRVANALAN** [comment]
Hi, thanks for your message. This flag was intended for addressing the occlusion ambiguity, though in the final submission I did not use that design. Please ignore the flag and let me know if there are more issues remaining.
